import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { LayoutNavbar } from "@/components/layouts/LayoutNavbar";
import { LayoutFooter } from "@/components/layouts/LayoutFooter";
import { QueryProvider } from "@/providers/QueryProvider";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <QueryProvider>
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <LayoutNavbar className="sticky top-0 z-50" />

                    <div className="px-4">{children}</div>

                    <LayoutFooter className="mt-auto" />
                </body>
            </QueryProvider>
        </html>
    );
}
